const operators = [
    {
        label: "equal to",
        value: "equal to",
        types: ["date", "integer", "number", "radio", "select", "switch", "text"],
        symbol: "=",
    },
    {
        label: "not equal to",
        value: "not equal",
        types: ["date", "integer", "number", "radio", "select", "switch", "text"],
        symbol: "<>",
    },
    {
        label: "contains",
        value: "contains",
        types: ["text"],
        symbol: "like",
    },
    {
        label: "does not contain",
        value: "not contains",
        types: ["text"],
        symbol: "not like",
    },
    {
        label: "begins with",
        value: "begins with",
        types: ["text"],
        symbol: "like",
    },
    {
        label: "ends with",
        value: "ends with",
        types: ["text"],
        symbol: "like",
    },
    {
        label: "less than",
        value: "less",
        types: ["number", "integer"],
        symbol: "<",
    },
    {
        label: "greater than",
        value: "greater",
        types: ["number", "integer"],
        symbol: ">",
    },
    {
        label: "less or equal to",
        value: "less equal",
        types: ["number", "integer"],
        symbol: "<=",
    },
    {
        label: "greater or equal to",
        value: "greater equal",
        types: ["number", "integer"],
        symbol: ">=",
    },
    {
        label: "before than",
        value: "before",
        types: ["date"],
        symbol: "<",
    },
    {
        label: "after than",
        value: "after",
        types: ["date"],
        symbol: ">",
    },
    {
        label: "before or equal to",
        value: "before_equal",
        types: ["date"],
        symbol: "<=",
    },
    {
        label: "after or equal to",
        value: "after_equal",
        types: ["date"],
        symbol: ">=",
    },
    {
        label: "is",
        value: "in",
        types: ["multiselect"],
        symbol: "in",
    },
    {
        label: "is not",
        value: "not in",
        types: ["multiselect"],
        symbol: "not in",
    },
    {
        label: "is null",
        value: "is null",
        types: ["date", "integer", "number", "multiselect", "radio", "select", "switch", "text"],
        symbol: "is null",
    },
    {
        label: "as null",
        value: "as null",
        types: ["update"],
        symbol: "=",
    },
    {
        label: "is not null",
        value: "not null",
        types: ["date", "integer", "number", "multiselect", "radio", "select", "switch", "text"],
        symbol: "is not null",
    },
    {
        label: "=",
        value: "equal to field",
        types: ["update"],
        symbol: "=",
    },
    {
        label: "Left Substring",
        value: "left substring",
        types: ["substring"],
        symbol: "=",
    },
    {
        label: "Right Substring",
        value: "right substring",
        types: ["substring"],
        symbol: "=",
    },
    {
        label: "Substring",
        value: "substring",
        types: ["substring"],
        symbol: "=",
    },
    {
        label: "Prefix",
        value: "prefix",
        types: ["prefix"],
        symbol: "||",
    },
    {
        label: "Suffix",
        value: "suffix",
        types: ["suffix"],
        symbol: "||",
    },
];

export default operators;
